apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  annotations:
    source-file: podinfo2.yaml
  name: podinfo2
  namespace: podinfo2
spec:
  interval: 5m0s
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
