apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  annotations:
    source-file: podinfo2-deployment.yaml
  name: podinfo2
  namespace: podinfo2
spec:
  interval: 5m0s
  prune: false
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: podinfo2
    namespace: podinfo2
  targetNamespace: podinfo2
  timeout: 3m0s
  wait: true
